services:
  voteit-app:
    build: ./voteit-service
    container_name: voteit-app-1
    ports:
      - "8089:8089"
    volumes:
      - ./voteit-service/posts_data.csv:/app/posts_data.csv
      - ./voteit-service/images:/app/images
    depends_on:
      - user-service

  user-service:
    build: ./user-service
    container_name: user-service-1
    ports:
      - "8090:8090"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - cadvisor
